### ISSUE TITLE
Question: compression?

### ISSUE THREAD

**Issue by xgdgsc** [queryverse/ExcelFiles.jl#23] opened 2019-01-26 04:16 UTC
Does it compress the data? From my test it seems to generate a file larger than raw csv files with the same content, which contradicts my previous experience with xlsx files.

**Comment by davidanthoff** [comment] 2019-01-31 20:48
We use @felipenoris' https://github.com/felipenoris/XLSX.jl package to write files, maybe he knows?

**Comment by felipenoris** [comment] 2019-01-31 21:01
@xgdgsc, the xlsx file format uses zip. What happens is that Excel may do some optimisation when saving data a file, and I might not replicate that in the Julia package. One way to check this is to just open the XLSX file using Excel, click on save, and check if the size of the file gets shrinked.

I once [fixed a bug](https://github.com/felipenoris/XLSX.jl/commit/74002f7764d512df957be8f25d892860936766d2) that made XLSX.jl generate big Excel files, and was related to string handling. I guess if you're not using Julia v1.0 you may not be using the release that has this bugfix.

Anyway, I would be happy to assist you if you provide a code example that reproduces the issue.

**Comment by xgdgsc** [comment] 2019-02-01 03:06
I' m using the latest julia and packages since I just had this server newly installed. I tried saving that excel inside libreoffice calc and it reduced the size to 1/10:

![deepinscreenshot_select-area_20190201110005](https://user-images.githubusercontent.com/1189869/52100010-9f922c80-2610-11e9-8687-f26a3e8cba7c.png)

The xlsx file is just saved by calling the naive 

```
using ExcelFiles, DataFrames
save("6.xlsx", df)
```

here are the files: 

[tmp.tar.gz](https://github.com/queryverse/ExcelFiles.jl/files/2819909/tmp.tar.gz)

And it' s interesting when just dragging the `gp_2019-01-27-13-13_6_mr01.xlsx` file to this issue. Github shows:

 
![deepinscreenshot_select-area_20190201110259](https://user-images.githubusercontent.com/1189869/52100174-5abac580-2611-11e9-8a12-eb7f61e824cc.png)

**Comment by felipenoris** [comment] 2019-02-15 02:26
@xgdgsc , I just pushed a fix to master branch of XLSX.jl . Can you check if it fixes your issue?

**Comment by xgdgsc** [comment] 2019-02-15 13:46
I get error when loading using `df = DataFrame(load("gp_2019-01-27-13-13_6_mr01.xlsx", "Sheet1"))`, does other packages also need to be updated?
```
UndefVarError: DataValueUnwrapper not defined

Stacktrace:
 [1] DataFrame(::ExcelFiles.ExcelFile) at /home/gsc/.julia/packages/DataFrames/KUWId/src/other/tables.jl:27
 [2] top-level scope at In[17]:1
```

**Comment by felipenoris** [comment] 2019-02-15 14:00
That doesn't look like an error on XLSX.jl. Also, since the fix is on `master` branch of XLSX.jl you should take that into consideration when dealing with ExcelFiles.jl . cc @davidanthoff

**Comment by xgdgsc** [comment] 2019-02-15 14:02
Also when loaded data from other format and trying to save using a simple `save` shows  the following error:
```
Error encountered while saving "test_.xlsx".
Fatal error:
ExcelFiles writer error: FileIO.save not defined
  Will try next writer.


Stacktrace:
 [1] handle_error(::FileIO.WriterError, ::FileIO.File{FileIO.DataFormat{:Excel}}) at /home/gsc/.julia/packages/FileIO/Y0Lre/src/error_handling.jl:80
 [2] handle_exceptions(::Array{Any,1}, ::String) at /home/gsc/.julia/packages/FileIO/Y0Lre/src/error_handling.jl:75
 [3] #save#30(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::FileIO.File{FileIO.DataFormat{:Excel}}, ::DataFrame) at /home/gsc/.julia/packages/FileIO/Y0Lre/src/loadsave.jl:217
 [4] save(::FileIO.File{FileIO.DataFormat{:Excel}}, ::DataFrame) at /home/gsc/.julia/packages/FileIO/Y0Lre/src/loadsave.jl:199
 [5] #save#15(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::String, ::DataFrame) at /home/gsc/.julia/packages/FileIO/Y0Lre/src/loadsave.jl:118
 [6] save(::String, ::DataFrame) at /home/gsc/.julia/packages/FileIO/Y0Lre/src/loadsave.jl:118
 [7] top-level scope at In[37]:21
```

**Comment by davidanthoff** [comment] 2019-02-15 17:48
@xgdgsc Could you try to update all your packages? And post what versions of packages are installed?

I've seen other reports with this `DataValueUnwrapper` error, and they seem to have gone away when people update their packages. I don't really know what is going on there, maybe there was a Tables.jl release that had a bug? The whole integration story between Query and DataFrames has moved to Tables.jl a while ago, and I don't really understand that code anymore...

**Comment by xgdgsc** [comment] 2019-02-16 02:50
I rebooted and ran a `Pkg.update()`. Loading works now. But saving would give the same error as above.

**Comment by davidanthoff** [comment] 2019-02-16 03:03
@xgdgsc can you post the exact versions of the packages that you are using? And ideally the exact code you are trying to run?

**Comment by xgdgsc** [comment] 2019-02-16 07:02
Thanks. After cloning latest https://github.com/queryverse/ExcelFiles.jl.git it works. Now I can confirm compression works now. I don' t know why my ExcelFiles is stuck at 0.6.1 even after running Pkg.update().

**Comment by felipenoris** [comment] 2019-02-16 14:48
Good to hear that! I just tagged a new version for XLSX.jl .

Thanks a lot! Many people will benefit from this fix!

**Closed** 2019-02-17 01:52 UTC
