### ISSUE TITLE
A way to handle excel sheets with non-unique headers when importing into dataframes?

### ISSUE THREAD

**Issue by ianshmean** [queryverse/ExcelFiles.jl#15] opened 2018-09-13 20:00 UTC
If the excel sheet you're trying to read in has non-unique headers, DataFrames raises an error.

`duplicate field name in NamedTuple: "columnname" is not unique`

What's the correct way to handle this? Is it possible to force the process to make the headers unique?

**Comment by nicoleepp** [comment] 2018-09-25 18:17
`colnames` seems to already be an option for ExcelFiles (after #18 fixes a related error). 

That being said, it would be nice if ExcelFiles supported non-unique headers without requiring re-names.

**Comment by davidanthoff** [comment] 2018-10-28 00:36
I think the assumption that column names are unique is really deeply embedded throughout the whole data system in julia, so I think the only real option here is to use ``colnames`` to make sure that what ExcelFiles produces has unique headers... I've merged @nicoleepp's fix for the ``colnames`` error, and I think beyond that this is a "by design" issue.

I'm closing this issue because I don't see anything else we can do on this.

**Closed by davidanthoff** 2018-10-28 00:36 UTC
Labels: enhancement
